const all_students = [
  {
    id: "#1236",
    avatar: "https://reqres.in/img/faces/7-image.jpg",
    first_name: "Michael",
    middle_name: "Michael",
    last_name: "Lawson",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Lawson",
    parent_number: "1234567891",
    parent_email: "michael.lawson@reqres.in",
    fees_status: "Paid",
  },
  {
    id: "#1235",
    avatar: "https://reqres.in/img/faces/8-image.jpg",
    first_name: "Lindsay",
    middle_name: "Lindsay",
    last_name: "Ferguson",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Ferguson",
    parent_number: "1234567891",
    parent_email: "lindsay.ferguson@reqres.in",
    fees_status: "Canceled",
  },
  {
    id: "#1234",
    avatar: "https://reqres.in/img/faces/9-image.jpg",
    first_name: "Tobias",
    middle_name: "Tobias",
    last_name: "Funke",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Funke",
    parent_number: "1234567891",
    parent_email: "tobias.funke@reqres.in",
    fees_status: "Paid",
  },
  {
    id: "#1233",
    avatar: "https://reqres.in/img/faces/10-image.jpg",
    first_name: "Byron",
    middle_name: "Byron",
    last_name: "Fields",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Fields",
    parent_number: "1234567891",
    parent_email: "byron.fields@reqres.in",
    fees_status: "Refunded",
  },
  {
    id: "#1232",
    avatar: "https://reqres.in/img/faces/11-image.jpg",
    first_name: "George",
    middle_name: "George",
    last_name: "Edwards",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Edwards",
    parent_number: "1234567891",
    parent_email: "george.edwards@reqres.in",
    fees_status: "Canceled",
  },
  {
    id: "#1231",
    avatar: "https://reqres.in/img/faces/12-image.jpg",
    first_name: "Rachel",
    middle_name: "Rachel",
    last_name: "Howell",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Howell",
    parent_number: "1234567891",
    parent_email: "rachel.howell@reqres.in",
    fees_status: "Paid",
  },
  {
    id: "#1236",
    avatar: "https://reqres.in/img/faces/7-image.jpg",
    first_name: "Michael",
    middle_name: "Michael",
    last_name: "Lawson",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Lawson",
    parent_number: "1234567891",
    parent_email: "michael.lawson@reqres.in",
    fees_status: "Paid",
  },
  {
    id: "#1235",
    avatar: "https://reqres.in/img/faces/8-image.jpg",
    first_name: "Lindsay",
    middle_name: "Lindsay",
    last_name: "Ferguson",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Ferguson",
    parent_number: "1234567891",
    parent_email: "lindsay.ferguson@reqres.in",
    fees_status: "Canceled",
  },
  {
    id: "#1234",
    avatar: "https://reqres.in/img/faces/9-image.jpg",
    first_name: "Tobias",
    middle_name: "Tobias",
    last_name: "Funke",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Funke",
    parent_number: "1234567891",
    parent_email: "tobias.funke@reqres.in",
    fees_status: "Paid",
  },
  {
    id: "#1233",
    avatar: "https://reqres.in/img/faces/10-image.jpg",
    first_name: "Byron",
    middle_name: "Byron",
    last_name: "Fields",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Fields",
    parent_number: "1234567891",
    parent_email: "byron.fields@reqres.in",
    fees_status: "Refunded",
  },
  {
    id: "#1232",
    avatar: "https://reqres.in/img/faces/11-image.jpg",
    first_name: "George",
    middle_name: "George",
    last_name: "Edwards",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Edwards",
    parent_number: "1234567891",
    parent_email: "george.edwards@reqres.in",
    fees_status: "Canceled",
  },
  {
    id: "#1231",
    avatar: "https://reqres.in/img/faces/12-image.jpg",
    first_name: "Rachel",
    middle_name: "Rachel",
    last_name: "Howell",
    birth_date: "1 Nov, 10:20 AM",
    parent_name: "Howell",
    parent_number: "1234567891",
    parent_email: "rachel.howell@reqres.in",
    fees_status: "Paid",
  },
];

export default all_students;
